// tuning_overrides.mjs — per-song tunings documented OUTSIDE the charts
// themselves (curated tuning archives, artist interviews, corroborated tabs).
// Researched 2026-07-02; every entry carries its source. Applied by
// build_manifest.mjs BELOW tab-label evidence (a transcription's own labels
// describe that arrangement) but ABOVE prose declarations, scraper metadata,
// and site conventions.
//
// Primary sources:
//   NY  = https://hyperrust.org/Music/NeilTunings.html (curated master list —
//         authoritative even though hyperrust's chart pages are weak)
//   Entries marked with other URLs cite interviews/corroborated tabs.

// [artist, title (library exact), tuningId or spelling, note]
export const TUNING_OVERRIDES = [
  // --- Father John Misty (Tyler 2026-07-02; live covers played a full step down) ---
  ["Father John Misty", "The Night Josh Tillman Came To Our Apartment", "dStandard", "UG meta + chart prose agree"],
  ["Father John Misty", "Heart-Shaped Box", "dStandard", "FJM live cover of Nirvana; chart body is the Nirvana transcription"],
  ["Father John Misty", "Modern Man", "dStandard", "FJM live cover of Arcade Fire; chart body is the AF transcription"],

  // --- Neil Young (source: NY unless noted) ---
  ["Neil Young", "Albuquerque", "dropD", ""],
  ["Neil Young", "Already One", "dropD", ""],
  ["Neil Young", "Ambulance Blues", "dStandard", ""],
  ["Neil Young", "Bandit", "A# F A# D# G A#", "Greendale — 2 steps below double drop D"],
  ["Neil Young", "Captain Kennedy", "doubleDropD", ""],
  ["Neil Young", "Cinnamon Girl", "doubleDropD", ""],
  ["Neil Young", "Cortez The Killer", "doubleDropD", ""],
  ["Neil Young", "Cowgirl In The Sand", "dStandard", "acoustic arrangement"],
  ["Neil Young", "Dance Dance Dance", "dStandard", ""],
  ["Neil Young", "Deep Forbidden Lake", "dStandard", ""],
  ["Neil Young", "Dont Be Denied", "dStandard", "acoustic arrangement"],
  ["Neil Young", "Dont Let It Bring You Down", "C G C F A C", "step below double drop D"],
  ["Neil Young", "Down By The River", "doubleDropD", "disputed: lesson sites vs hyperrust omission"],
  ["Neil Young", "Dreamin Man", "doubleDropD", ""],
  ["Neil Young", "Expecting To Fly", "dStandard", ""],
  ["Neil Young", "Give Me Strength", "dropD", ""],
  ["Neil Young", "Goin Back", "doubleDropD", ""],
  ["Neil Young", "Hangin On A Limb", "D G C F A A", "1st string up to match 2nd"],
  ["Neil Young", "Harvest Moon", "dropD", "also acousticguitar.com lesson"],
  ["Neil Young", "Mr Soul", "doubleDropD", "https://hyperrust.org/OLD-ChordTab/MrSoul.html"],
  ["Neil Young", "The Last Trip To Tulsa", "dStandard", ""],
  ["Neil Young", "Little Wing", "dStandard", "Neil's arrangement"],
  ["Neil Young", "Long May You Run", "dStandard", ""],
  ["Neil Young", "Love Is A Rose", "dStandard", ""],
  ["Neil Young", "Motion Pictures For Carrie", "dStandard", ""],
  ["Neil Young", "Natural Beauty", "doubleDropD", ""],
  ["Neil Young", "Ohio", "doubleDropD", ""],
  ["Neil Young", "Old Man", "dStandard", ""],
  ["Neil Young", "On The Beach", "dStandard", "acoustic arrangement"],
  ["Neil Young", "On The Way Home", "dStandard", "acoustic arrangement"],
  ["Neil Young", "One Of These Days", "doubleDropD", ""],
  ["Neil Young", "Pardon My Heart", "C G C F A C", "https://hyperrust.org/OLD-ChordTab/PardonHeart.html + gtdb.org/cgcfac"],
  ["Neil Young", "Pocahontas", "C G C F A D", "'Slack D' live arrangement"],
  ["Neil Young", "Powderfinger", "dStandard", "acoustic arrangement"],
  ["Neil Young", "Revolution Blues", "dStandard", ""],
  ["Neil Young", "Rockin In The Free World", "dStandard", "acoustic arrangement"],
  ["Neil Young", "Roll Another Number", "dStandard", ""],
  ["Neil Young", "Round And Round", "dStandard", ""],
  ["Neil Young", "Someday", "dStandard", ""],
  ["Neil Young", "Southern Man", "dStandard", ""],
  ["Neil Young", "Star Of Bethlehem", "dropD", ""],
  ["Neil Young", "Sugar Mountain", "dStandard", ""],
  ["Neil Young", "Tell Me Why", "dStandard", "the one that started this pass"],
  ["Neil Young", "Tonights The Night", "dropD", ""],
  ["Neil Young", "War Of Man", "doubleDropD", ""],
  ["Neil Young", "When You Dance I Can Really Love", "doubleDropD", ""],
  ["Neil Young", "You And Me", "dropD", ""],
  ["Neil Young", "Lets Roll", "standard", "repairs garbage metadata (letters were fret symbols)"],
  ["Neil Young", "After Berlin", "doubleDropD", "listed as 'Berlin' on NY"],
  ["Neil Young", "California Sunset", "dStandard", ""],
  ["Neil Young", "Daddy Went Walkin", "dropD", ""],
  ["Neil Young", "Dream Machine", "doubleDropD", "aka Live To Ride/Friend Of Mine — corrects Drop D"],
  ["Neil Young", "Feel Your Love", "dStandard", ""],
  ["Neil Young", "Grandpas Interview", "doubleDropD", ""],
  ["Neil Young", "Great Divide", "dStandard", "listed as 'The Great Divide'"],
  ["Neil Young", "The Great Divide", "dStandard", ""],
  ["Neil Young", "Hold Back The Tears", "dStandard", ""],
  ["Neil Young", "Homegrown", "dropD", ""],
  ["Neil Young", "Inca Queen", "doubleDropD", ""],
  ["Neil Young", "Interstate", "dStandard", ""],
  ["Neil Young", "La", "dStandard", "acoustic arrangement"],
  ["Neil Young", "L.A.", "dStandard", "acoustic arrangement"],
  ["Neil Young", "Long Walk Home", "dStandard", ""],
  ["Neil Young", "Name Of Love", "dStandard", ""],
  ["Neil Young", "New Mama", "dropD", ""],
  ["Neil Young", "Old Ways", "dStandard", ""],
  ["Neil Young", "The Old Homestead", "dropD", ""],
  ["Neil Young", "Prime Of Life", "dropD", ""],
  ["Neil Young", "Ride My Llama", "doubleDropD", ""],
  ["Neil Young", "The Ways Of Love", "dropD", ""],
  ["Neil Young", "Western Hero", "dStandard", ""],

  // --- indie lane (sources per entry) ---
  ["Big Thief", "Simulation Swarm", "C# G# C# F A# C#", "https://gtdb.org/csascsfgscs"],
  ["Big Thief", "Watering", "Eb A D G B E", "only the low string drops — corrects Eb Standard"],
  ["Adrianne Lenker", "Anything", "D# A# D# G A# D#", "open D shifted up a half step"],
  ["Kurt Vile", "Wakin On A Pretty Day", "ebStandard", "3+ independent sources"],
  ["Kurt Vile", "Girl Called Alex", "standard", "documented plain standard — corrects D Standard"],
  ["MJ Lenderman", "You Are Every Girl To Me", "C G D G G E", "https://guitar.com/features/interviews/mj-lenderman-interview-manning-fireworks/"],
  ["Alex G", "Harvey", "dropD", "multiple UG tabs agree — corrects D Standard"],
  ["Alex G", "Memory", "C G C G B E", "https://www.e-chords.com/en/tabs/alex-g/memory"],

  // --- Songsterr audit 2026-07-05 (machine-triaged 2026-07-26): records whose
  // own tuning evidence was weak (meta/convention), single-version only,
  // Songsterr's absolute per-track tuning as the citation. ---
  ["Big Thief", "Velvet Ring", "D A D F# A D", "songsterr audit 2026-07-05 (128849 views) https://www.songsterr.com/a/wsa/x-tab-s555975"],
  ["Elliott Smith", "clementine", "C G C E A D", "songsterr audit 2026-07-05 (85842 views) https://www.songsterr.com/a/wsa/x-tab-s410476"],
  ["Alex G", "Sarah", "D# G# C# F# A# D#", "songsterr audit 2026-07-05 (37782 views) https://www.songsterr.com/a/wsa/x-tab-s577839"],
  ["Adrianne Lenker", "Forwards Beckon Rebound", "D A D F# A D", "songsterr audit 2026-07-05 (22422 views) https://www.songsterr.com/a/wsa/x-tab-s744175"],
  ["Elliott Smith", "everything reminds me of her", "D G C F A D", "songsterr audit 2026-07-05 (22408 views) https://www.songsterr.com/a/wsa/x-tab-s410484"],
  ["Elliott Smith", "Ballad of Big Nothing", "C G C E C E", "songsterr audit 2026-07-05 (20107 views) https://www.songsterr.com/a/wsa/x-tab-s17351"],
  ["Adrianne Lenker", "Half Return", "D# A# D# G A# D#", "songsterr audit 2026-07-05 (15220 views) https://www.songsterr.com/a/wsa/x-tab-s709179"],
  ["Sun Kil Moon", "Alesund", "C# G# C# D# A# C", "songsterr audit 2026-07-05 (14932 views) https://www.songsterr.com/a/wsa/x-tab-s80209"],
  ["Elliott Smith", "la", "E A D G B E", "songsterr audit 2026-07-05 (12129 views) https://www.songsterr.com/a/wsa/x-tab-s59811"],
  ["Nick Drake", "From The Morning", "B E B E B E", "songsterr audit 2026-07-05 (10866 views) https://www.songsterr.com/a/wsa/x-tab-s48500"],
  ["Red House Painters", "Katy Song (Ver 2)", "C# G# C# F A# D#", "songsterr audit 2026-07-05 (10443 views) https://www.songsterr.com/a/wsa/x-tab-s707729"],
  ["Red House Painters", "Katy Song (Ver 3)", "C# G# C# F A# D#", "songsterr audit 2026-07-05 (10443 views) https://www.songsterr.com/a/wsa/x-tab-s707729"],
  ["Red House Painters", "Katy Song (Ver 4)", "C# G# C# F A# D#", "songsterr audit 2026-07-05 (10443 views) https://www.songsterr.com/a/wsa/x-tab-s707729"],
  ["Red House Painters", "Katy Song (Ver 6)", "C# G# C# F A# D#", "songsterr audit 2026-07-05 (10443 views) https://www.songsterr.com/a/wsa/x-tab-s707729"],
  ["Paul McCartney", "Jenny Wren", "D G C F A D", "songsterr audit 2026-07-05 (9916 views) https://www.songsterr.com/a/wsa/x-tab-s50158"],
  ["Alex G", "Advice", "D G C F A D", "songsterr audit 2026-07-05 (9832 views) https://www.songsterr.com/a/wsa/x-tab-s541285"],
  ["Nick Drake", "Which Will", "B F# B E B D#", "songsterr audit 2026-07-05 (8393 views) https://www.songsterr.com/a/wsa/x-tab-s76855"],
  ["Bob Dylan", "Buckets of Rain", "E B E G# B E", "songsterr audit 2026-07-05 (8023 views) https://www.songsterr.com/a/wsa/x-tab-s27198"],
  ["Adrianne Lenker", "My Angel", "D A D F# B D", "songsterr audit 2026-07-05 (6851 views) https://www.songsterr.com/a/wsa/x-tab-s1004493"],
  ["Fleetwood Mac", "Never Going Back Again", "D A D G B E", "songsterr audit 2026-07-05 (6221 views) https://www.songsterr.com/a/wsa/x-tab-s2560871"],
  ["Sun Kil Moon", "Duk Koo Kim (Ver 1)", "C# G# C# F# A# D#", "songsterr audit 2026-07-05 (5389 views) https://www.songsterr.com/a/wsa/x-tab-s944843"],
  ["Sun Kil Moon", "Duk Koo Kim (Ver 2)", "C# G# C# F# A# D#", "songsterr audit 2026-07-05 (5389 views) https://www.songsterr.com/a/wsa/x-tab-s944843"],
  ["Nick Drake", "Road", "D G D D A D", "songsterr audit 2026-07-05 (5307 views) https://www.songsterr.com/a/wsa/x-tab-s420475"],
  ["Fleetwood Mac", "Bleed To Love Her", "D# G# C# F# A# D#", "songsterr audit 2026-07-05 (5096 views) https://www.songsterr.com/a/wsa/x-tab-s417395"],
  ["Elliott Smith", "roman candle", "E A D G B E", "songsterr audit 2026-07-05 (4839 views) https://www.songsterr.com/a/wsa/x-tab-s18468"],
  ["Elliott Smith", "i don't think i'm ever gonna figure it out", "E A D G B E", "songsterr audit 2026-07-05 (4626 views) https://www.songsterr.com/a/wsa/x-tab-s529603"],
  ["Nick Drake", "Hazey Jane I", "C G C F C E", "songsterr audit 2026-07-05 (4108 views) https://www.songsterr.com/a/wsa/x-tab-s420477"],
  ["Nick Drake", "Parasite", "D A D G A D", "songsterr audit 2026-07-05 (3829 views) https://www.songsterr.com/a/wsa/x-tab-s6255"],
  ["Alex G", "Change", "C G C F A D", "songsterr audit 2026-07-05 (3672 views) https://www.songsterr.com/a/wsa/x-tab-s670064"],
  ["Elliott Smith", "rose parade", "E A D G B E", "songsterr audit 2026-07-05 (3111 views) https://www.songsterr.com/a/wsa/x-tab-s17911"],
  ["Pavement", "Cut Your Hair", "C G D A B E", "songsterr audit 2026-07-05 (3096 views) https://www.songsterr.com/a/wsa/x-tab-s459837"],
  ["John Lennon", "Stand by Me", "D A D G B E", "songsterr audit 2026-07-05 (2697 views) https://www.songsterr.com/a/wsa/x-tab-s86010"],
  ["Elliott Smith", "sweet adeline", "E A D G B E", "songsterr audit 2026-07-05 (2313 views) https://www.songsterr.com/a/wsa/x-tab-s18016"],
  ["Big Thief", "Shark Smile", "F# B E A C# F#", "songsterr audit 2026-07-05 (2202 views) https://www.songsterr.com/a/wsa/x-tab-s548889"],
  ["Nick Drake", "Man In A Shed", "B E B E B E", "songsterr audit 2026-07-05 (2201 views) https://www.songsterr.com/a/wsa/x-tab-s420480"],
  ["Paul McCartney", "Uncle Albert/Admiral Halsey", "D A D G B E", "songsterr audit 2026-07-05 (2153 views) https://www.songsterr.com/a/wsa/x-tab-s488105"],
  ["Elliott Smith", "independence day", "E A D G B E", "songsterr audit 2026-07-05 (2099 views) https://www.songsterr.com/a/wsa/x-tab-s797167"],
  ["Paul McCartney", "Too Many People", "D G C F A D", "songsterr audit 2026-07-05 (2037 views) https://www.songsterr.com/a/wsa/x-tab-s495844"],
  ["Elliott Smith", "stupidity tries", "E A D G B E", "songsterr audit 2026-07-05 (2005 views) https://www.songsterr.com/a/wsa/x-tab-s802577"],
  ["Elliott Smith", "condor ave", "E A D G B E", "songsterr audit 2026-07-05 (1649 views) https://www.songsterr.com/a/wsa/x-tab-s990721"],
  ["Sun Kil Moon", "Carry Me Ohio", "D A D G A D", "songsterr audit 2026-07-05 (1534 views) https://www.songsterr.com/a/wsa/x-tab-s251826"],
  ["Bob Dylan", "Corrina, Corrina", "D A D F# A D", "songsterr audit 2026-07-05 (1513 views) https://www.songsterr.com/a/wsa/x-tab-s410016"],
  ["Father John Misty", "Real Love Baby", "D A D G B E", "songsterr audit 2026-07-05 (1486 views) https://www.songsterr.com/a/wsa/x-tab-s473239"],
  ["Paul McCartney", "Coming Up", "D# G# C# F# A# D#", "songsterr audit 2026-07-05 (1473 views) https://www.songsterr.com/a/wsa/x-tab-s651672"],
  ["Elliott Smith", "kiwi maddog 20/20", "E A D G B E", "songsterr audit 2026-07-05 (1398 views) https://www.songsterr.com/a/wsa/x-tab-s410474"],
  ["Pavement", "Stereo", "D A D A B E", "songsterr audit 2026-07-05 (1381 views) https://www.songsterr.com/a/wsa/x-tab-s462406"],
  ["Neil Young", "A Man Needs A Maid", "D A D G B E", "songsterr audit 2026-07-05 (1359 views) https://www.songsterr.com/a/wsa/x-tab-s20581"],
  ["Bob Dylan", "Masters of War", "D A D G B E", "songsterr audit 2026-07-05 (1350 views) https://www.songsterr.com/a/wsa/x-tab-s371212"],
  ["Sun Kil Moon", "Salvador Sanchez (Ver 1)", "C G C F A D", "songsterr audit 2026-07-05 (1286 views) https://www.songsterr.com/a/wsa/x-tab-s2026935"],
  ["Sun Kil Moon", "Salvador Sanchez (Ver 2)", "C G C F A D", "songsterr audit 2026-07-05 (1286 views) https://www.songsterr.com/a/wsa/x-tab-s2026935"],
  ["Bob Dylan", "I Was Young When I Left Home", "D G D G B D", "songsterr audit 2026-07-05 (1249 views) https://www.songsterr.com/a/wsa/x-tab-s410022"],
  ["Pavement", "Cream Of Gold", "D A D G B E", "songsterr audit 2026-07-05 (1157 views) https://www.songsterr.com/a/wsa/x-tab-s15575"],
  ["Jason Isbell", "Cover Me Up", "D# A# D# G A# D#", "songsterr audit 2026-07-05 (1156 views) https://www.songsterr.com/a/wsa/x-tab-s1049633"],
  ["Neil Young", "The Loner", "D A D G B D", "songsterr audit 2026-07-05 (1040 views) https://www.songsterr.com/a/wsa/x-tab-s21663"],
  ["Nick Drake", "Fly", "B E B E B E", "songsterr audit 2026-07-05 (1017 views) https://www.songsterr.com/a/wsa/x-tab-s48494"],
  ["Elliott Smith", "junk bond trader", "E A D G B E", "songsterr audit 2026-07-05 (1009 views) https://www.songsterr.com/a/wsa/x-tab-s846143"],
  ["Grizzly Bear", "Southern Point", "D A D F# B D", "songsterr audit 2026-07-05 (959 views) https://www.songsterr.com/a/wsa/x-tab-s70830"],
  ["Elliott Smith", "can't make a sound", "E A D G B E", "songsterr audit 2026-07-05 (911 views) https://www.songsterr.com/a/wsa/x-tab-s861084"],
  ["Elliott Smith", "i better be quiet now", "E A D G B E", "songsterr audit 2026-07-05 (844 views) https://www.songsterr.com/a/wsa/x-tab-s183299"],
  ["Fleetwood Mac", "Shake Your Moneymaker", "E B E G# B E", "songsterr audit 2026-07-05 (787 views) https://www.songsterr.com/a/wsa/x-tab-s482818"],
  ["Alex G", "Powerful Man", "D A D G A D", "songsterr audit 2026-07-05 (769 views) https://www.songsterr.com/a/wsa/x-tab-s1770409"],
  ["George Harrison", "Your Love Is Forever", "D A D F# A D", "songsterr audit 2026-07-05 (765 views) https://www.songsterr.com/a/wsa/x-tab-s36393"],
  ["Nick Drake", "Clothes Of Sand", "E A D G A E", "songsterr audit 2026-07-05 (760 views) https://www.songsterr.com/a/wsa/x-tab-s48496"],
  ["Elliott Smith", "everybody cares, everybody understands", "E A D G B E", "songsterr audit 2026-07-05 (739 views) https://www.songsterr.com/a/wsa/x-tab-s848262"],
  ["Elliott Smith", "last call", "D# G# C# F# A# D#", "songsterr audit 2026-07-05 (695 views) https://www.songsterr.com/a/wsa/x-tab-s192185"],
  ["Elliott Smith", "i didn't understand", "E A D G B E", "songsterr audit 2026-07-05 (655 views) https://www.songsterr.com/a/wsa/x-tab-s33919"],
  ["Sun Kil Moon", "Carissa", "C G C E G C", "songsterr audit 2026-07-05 (625 views) https://www.songsterr.com/a/wsa/x-tab-s398339"],
  ["Bob Dylan", "Blind Willie McTell", "D# G# C# F# A# D#", "songsterr audit 2026-07-05 (602 views) https://www.songsterr.com/a/wsa/x-tab-s410024"],
  ["Bob Dylan", "One Too Many Mornings", "E A C# E A C#", "songsterr audit 2026-07-05 (585 views) https://www.songsterr.com/a/wsa/x-tab-s59505"],
  ["Pavement", "In The Mouth A Desert", "C G D G B E", "songsterr audit 2026-07-05 (576 views) https://www.songsterr.com/a/wsa/x-tab-s1099098"],
  ["Nick Drake", "Cello Song", "E A D F# B E", "songsterr audit 2026-07-05 (548 views) https://www.songsterr.com/a/wsa/x-tab-s48497"],
  ["Elliott Smith", "strung out again", "E A D G B E", "songsterr audit 2026-07-05 (530 views) https://www.songsterr.com/a/wsa/x-tab-s183329"],
  ["Pavement", "Stop Breathin", "D A D G B E", "songsterr audit 2026-07-05 (527 views) https://www.songsterr.com/a/wsa/x-tab-s15375"],
  ["Sun Kil Moon", "Glenn Tipton (Ver 1)", "D A D G A D", "songsterr audit 2026-07-05 (482 views) https://www.songsterr.com/a/wsa/x-tab-s251827"],
  ["John Lennon", "Give Peace a Chance", "D# G# C# F# A# D#", "songsterr audit 2026-07-05 (469 views) https://www.songsterr.com/a/wsa/x-tab-s11953"],
  ["Bob Dylan", "Oxford Town", "D A D F# A D", "songsterr audit 2026-07-05 (463 views) https://www.songsterr.com/a/wsa/x-tab-s83838"],
  ["Bob Dylan", "Forever Young", "D# G# C# F# A# D#", "songsterr audit 2026-07-05 (382 views) https://www.songsterr.com/a/wsa/x-tab-s59506"],
  ["Elliott Smith", "baby britain", "E A D G B E", "songsterr audit 2026-07-05 (370 views) https://www.songsterr.com/a/wsa/x-tab-s410475"],
  ["Pavement", "Embassy Row", "C G D G B E", "songsterr audit 2026-07-05 (350 views) https://www.songsterr.com/a/wsa/x-tab-s1637650"],
  ["Elliott Smith", "waltz #1", "D# G# C# F# A# D#", "songsterr audit 2026-07-05 (330 views) https://www.songsterr.com/a/wsa/x-tab-s867087"],
  ["Kurt Vile", "Check Baby", "E A D G B E", "songsterr audit 2026-07-05 (328 views) https://www.songsterr.com/a/wsa/x-tab-s866020"],
  ["Elliott Smith", "shooting star", "E A D G B E", "songsterr audit 2026-07-05 (316 views) https://www.songsterr.com/a/wsa/x-tab-s1433039"],
  ["Red House Painters", "Brown Eyes (Ver 2)", "D# G C F A# D", "songsterr audit 2026-07-05 (297 views) https://www.songsterr.com/a/wsa/x-tab-s398338"],
  ["Fleetwood Mac", "Oh Daddy", "E A D G B D", "songsterr audit 2026-07-05 (294 views) https://www.songsterr.com/a/wsa/x-tab-s417399"],
  ["Elliott Smith", "a question mark", "E A D G B E", "songsterr audit 2026-07-05 (283 views) https://www.songsterr.com/a/wsa/x-tab-s805397"],
  ["Fleetwood Mac", "Over My Head", "D A D G B E", "songsterr audit 2026-07-05 (278 views) https://www.songsterr.com/a/wsa/x-tab-s417396"],
  ["Paul McCartney", "Yesterday", "D G C F A D", "songsterr audit 2026-07-05 (274 views) https://www.songsterr.com/a/wsa/x-tab-s64356"],
  ["Sun Kil Moon", "Heron Blue", "F A C G C E", "songsterr audit 2026-07-05 (269 views) https://www.songsterr.com/a/wsa/x-tab-s61290"],
  ["Sun Kil Moon", "Heron Blue", "F A C G C E", "songsterr audit 2026-07-05 (269 views) https://www.songsterr.com/a/wsa/x-tab-s61290"],
  ["Pavement", "Fight This Generation", "C A D G B E", "songsterr audit 2026-07-05 (267 views) https://www.songsterr.com/a/wsa/x-tab-s15002"],
  ["Sun Kil Moon", "Dramamine (Live)", "C G C F A D", "songsterr audit 2026-07-05 (261 views) https://www.songsterr.com/a/wsa/x-tab-s1083025"],
  ["Sun Kil Moon", "Dramamine (Ver 1)", "C G C F A D", "songsterr audit 2026-07-05 (261 views) https://www.songsterr.com/a/wsa/x-tab-s1083025"],
  ["Elliott Smith", "amity", "E A D G B E", "songsterr audit 2026-07-05 (254 views) https://www.songsterr.com/a/wsa/x-tab-s862759"],
  ["Red House Painters", "Down Through (Ver 2)", "C A D G B E", "songsterr audit 2026-07-05 (252 views) https://www.songsterr.com/a/wsa/x-tab-s398342"],
  ["Uncle Tupelo", "Sandusky", "D A D G B E", "songsterr audit 2026-07-05 (252 views) https://www.songsterr.com/a/wsa/x-tab-s3844600"],
  ["Elliott Smith", "a distorted reality is now a necessity to be free", "E A D G B E", "songsterr audit 2026-07-05 (248 views) https://www.songsterr.com/a/wsa/x-tab-s1076857"],
  ["Elliott Smith", "alphabet town", "E A D G B E", "songsterr audit 2026-07-05 (238 views) https://www.songsterr.com/a/wsa/x-tab-s706036"],
  ["Neil Young", "For The Turnstiles", "D G C F A D", "songsterr audit 2026-07-05 (235 views) https://www.songsterr.com/a/wsa/x-tab-s457646"],
  ["Neil Young", "The Old Laughing Lady", "D A D G B D", "songsterr audit 2026-07-05 (235 views) https://www.songsterr.com/a/wsa/x-tab-s457963"],
  ["Nick Drake", "Time Of No Reply", "C F C F C F", "songsterr audit 2026-07-05 (229 views) https://www.songsterr.com/a/wsa/x-tab-s420476"],
  ["Red House Painters", "24 (Ver 2)", "C G C F A D", "songsterr audit 2026-07-05 (221 views) https://www.songsterr.com/a/wsa/x-tab-s751900"],
  ["Grizzly Bear", "Ready Able", "D A D F# B D", "songsterr audit 2026-07-05 (207 views) https://www.songsterr.com/a/wsa/x-tab-s59079"],
  ["Red House Painters", "Strawberry Hill (Ver 1)", "E A D G B E", "songsterr audit 2026-07-05 (173 views) https://www.songsterr.com/a/wsa/x-tab-s1035732"],
  ["Red House Painters", "Strawberry Hill (Ver 3)", "E A D G B E", "songsterr audit 2026-07-05 (173 views) https://www.songsterr.com/a/wsa/x-tab-s1035732"],
  ["Big Thief", "Los Angeles", "E A D G B E", "songsterr audit 2026-07-05 (164 views) https://www.songsterr.com/a/wsa/x-tab-s2500104"],
  ["Elliott Smith", "big decision", "E A D G B E", "songsterr audit 2026-07-05 (158 views) https://www.songsterr.com/a/wsa/x-tab-s880245"],
  ["Bob Dylan", "It's Alright, Ma (I'm Only Bleeding)", "D A D G B E", "songsterr audit 2026-07-05 (134 views) https://www.songsterr.com/a/wsa/x-tab-s4469054"],
  ["Sparklehorse", "King Of Nails", "D A D G B E", "songsterr audit 2026-07-05 (133 views) https://www.songsterr.com/a/wsa/x-tab-s863925"],
  ["MJ Lenderman", "On My Knees", "D G C F A D", "songsterr audit 2026-07-05 (132 views) https://www.songsterr.com/a/wsa/x-tab-s3672733"],
  ["Nick Drake", "Place To Be", "E B E A B E", "songsterr audit 2026-07-05 (132 views) https://www.songsterr.com/a/wsa/x-tab-s4969787"],
  ["Elliott Smith", "i can't answer you anymore", "E A D G B E", "songsterr audit 2026-07-05 (131 views) https://www.songsterr.com/a/wsa/x-tab-s802575"],
  ["Red House Painters", "Priest Alley Song (Ver 2)", "C# G# C# F# A# D#", "songsterr audit 2026-07-05 (117 views) https://www.songsterr.com/a/wsa/x-tab-s1083009"],
  ["Elliott Smith", "no name #4", "E A D G B E", "songsterr audit 2026-07-05 (115 views) https://www.songsterr.com/a/wsa/x-tab-s908044"],
  ["Sun Kil Moon", "Lily And Parrots", "D# G# C# F# A# D#", "songsterr audit 2026-07-05 (95 views) https://www.songsterr.com/a/wsa/x-tab-s2393934"],
  ["Red House Painters", "Mistress (Live)", "C G C F A D", "songsterr audit 2026-07-05 (93 views) https://www.songsterr.com/a/wsa/x-tab-s1096087"],
  ["Red House Painters", "Mistress (Ver 1)", "C G C F A D", "songsterr audit 2026-07-05 (93 views) https://www.songsterr.com/a/wsa/x-tab-s1096087"],
  ["Red House Painters", "Mistress (Ver 2)", "C G C F A D", "songsterr audit 2026-07-05 (93 views) https://www.songsterr.com/a/wsa/x-tab-s1096087"],
  ["Red House Painters", "Mistress (Ver 3)", "C G C F A D", "songsterr audit 2026-07-05 (93 views) https://www.songsterr.com/a/wsa/x-tab-s1096087"],
  ["Nick Drake", "Been Smoking Too Long", "D G D G B D", "songsterr audit 2026-07-05 (92 views) https://www.songsterr.com/a/wsa/x-tab-s420488"],
  ["Red House Painters", "San Geronimo (Ver 2)", "D G C F A D", "songsterr audit 2026-07-05 (88 views) https://www.songsterr.com/a/wsa/x-tab-s395968"],
  ["Sun Kil Moon", "Unlit Hallway (Live)", "E A D G B E", "songsterr audit 2026-07-05 (81 views) https://www.songsterr.com/a/wsa/x-tab-s2591559"],
  ["Red House Painters", "Things Mean A lot (Ver 1)", "E A D G B E", "songsterr audit 2026-07-05 (79 views) https://www.songsterr.com/a/wsa/x-tab-s1082870"],
  ["Red House Painters", "Things Mean A Lot (Ver 2)", "E A D G B E", "songsterr audit 2026-07-05 (79 views) https://www.songsterr.com/a/wsa/x-tab-s1082870"],
  ["Elliott Smith", "fond farewell", "E A D G B E", "songsterr audit 2026-07-05 (75 views) https://www.songsterr.com/a/wsa/x-tab-s183310"],
  ["Red House Painters", "Drop (Ver 1)", "E A D G B E", "songsterr audit 2026-07-05 (74 views) https://www.songsterr.com/a/wsa/x-tab-s1082886"],
  ["Red House Painters", "Drop (Ver 2)", "E A D G B E", "songsterr audit 2026-07-05 (74 views) https://www.songsterr.com/a/wsa/x-tab-s1082886"],
  ["Red House Painters", "Make Like Paper (Ver 2)", "D A D G A D", "songsterr audit 2026-07-05 (67 views) https://www.songsterr.com/a/wsa/x-tab-s398340"],
  ["Red House Painters", "Make Like Paper (Ver 3)", "D A D G A D", "songsterr audit 2026-07-05 (67 views) https://www.songsterr.com/a/wsa/x-tab-s398340"],
  ["Adrianne Lenker", "Symbol", "D A D G A D", "songsterr audit 2026-07-05 (64 views) https://www.songsterr.com/a/wsa/x-tab-s5574779"],
  ["Sun Kil Moon", "Dogs", "D# G# C# F# A# D#", "songsterr audit 2026-07-05 (64 views) https://www.songsterr.com/a/wsa/x-tab-s1083038"],
  ["Songs: Ohia", "Being In Love", "D# G# C# F# A# D#", "songsterr audit 2026-07-05 (62 views) https://www.songsterr.com/a/wsa/x-tab-s248583"],
  ["Pavement", "Ann Dont Cry", "D A D G B E", "songsterr audit 2026-07-05 (59 views) https://www.songsterr.com/a/wsa/x-tab-s14785"],
  ["Red House Painters", "Have You Forgotten (Ver 1)", "E A D G B E", "songsterr audit 2026-07-05 (54 views) https://www.songsterr.com/a/wsa/x-tab-s239190"],
  ["Red House Painters", "Have You Forgotten", "E A D G B E", "songsterr audit 2026-07-05 (54 views) https://www.songsterr.com/a/wsa/x-tab-s239190"],
  ["Red House Painters", "Evil (Ver 2)", "C G C F A D", "songsterr audit 2026-07-05 (52 views) https://www.songsterr.com/a/wsa/x-tab-s398343"],
  ["Silver Jews", "Strange Victory Strange Defeat", "D A D G B E", "songsterr audit 2026-07-05 (51 views) https://www.songsterr.com/a/wsa/x-tab-s1257540"],
  ["Grizzly Bear", "I Live With You", "D A D F# B D", "songsterr audit 2026-07-05 (46 views) https://www.songsterr.com/a/wsa/x-tab-s70829"],
  ["Nick Drake", "At The Chime Of A City Clock", "D# G# C# F# A# D#", "songsterr audit 2026-07-05 (43 views) https://www.songsterr.com/a/wsa/x-tab-s230675"],
  ["Pavement", "Perfume-V", "D A D A B E", "songsterr audit 2026-07-05 (40 views) https://www.songsterr.com/a/wsa/x-tab-s1764992"],
  ["Bob Dylan", "Dark Eyes", "D G C F A D", "songsterr audit 2026-07-05 (35 views) https://www.songsterr.com/a/wsa/x-tab-s371349"],
  ["Pavement", "Rattled By The Rush", "D A D A B E", "songsterr audit 2026-07-05 (33 views) https://www.songsterr.com/a/wsa/x-tab-s4831305"],
  ["Red House Painters", "Bubble (Live)", "E A D G B E", "songsterr audit 2026-07-05 (32 views) https://www.songsterr.com/a/wsa/x-tab-s1082864"],
  ["Red House Painters", "Bubble (Ver 1)", "E A D G B E", "songsterr audit 2026-07-05 (32 views) https://www.songsterr.com/a/wsa/x-tab-s1082864"],
  ["Sun Kil Moon", "I Watched The Film The Song Remains The Same", "E A B E B E", "songsterr audit 2026-07-05 (32 views) https://www.songsterr.com/a/wsa/x-tab-s1083039"],
  ["Sun Kil Moon", "I Watched The Film The Song Remains The Same", "E A B E B E", "songsterr audit 2026-07-05 (32 views) https://www.songsterr.com/a/wsa/x-tab-s1083039"],
  ["Red House Painters", "I Am A Rock (Ver 1)", "E A D G B E", "songsterr audit 2026-07-05 (29 views) https://www.songsterr.com/a/wsa/x-tab-s1587814"],
  ["Sun Kil Moon", "Space Travel Is Boring", "D# G# C# F# A# D#", "songsterr audit 2026-07-05 (28 views) https://www.songsterr.com/a/wsa/x-tab-s5301594"],
  ["Sun Kil Moon", "Space Travel Is Boring", "D# G# C# F# A# D#", "songsterr audit 2026-07-05 (28 views) https://www.songsterr.com/a/wsa/x-tab-s5301594"],
  ["Red House Painters", "Waterkill (Ver 1)", "E A D G B E", "songsterr audit 2026-07-05 (25 views) https://www.songsterr.com/a/wsa/x-tab-s1082869"],
  ["Red House Painters", "New Jersey (Ver 2)", "D A D G B E", "songsterr audit 2026-07-05 (24 views) https://www.songsterr.com/a/wsa/x-tab-s1382511"],
  ["Elliott Smith", "how to take a fall", "E A D G B E", "songsterr audit 2026-07-05 (22 views) https://www.songsterr.com/a/wsa/x-tab-s802717"],
  ["Sun Kil Moon", "Lost Verses (Live) (Live)", "E B E G# B E", "songsterr audit 2026-07-05 (21 views) https://www.songsterr.com/a/wsa/x-tab-s251823"],
  ["Grizzly Bear", "Foreground", "D A D F# A D", "songsterr audit 2026-07-05 (20 views) https://www.songsterr.com/a/wsa/x-tab-s418362"],
  ["Neil Young", "T-bone", "D A D G B D", "songsterr audit 2026-07-05 (17 views) https://www.songsterr.com/a/wsa/x-tab-s423491"],
  ["Elliott Smith", "king's crossing", "E A D G B E", "songsterr audit 2026-07-05 (16 views) https://www.songsterr.com/a/wsa/x-tab-s410478"],
  ["John Lennon", "Real Love", "D# G# C# F# A# D#", "songsterr audit 2026-07-05 (15 views) https://www.songsterr.com/a/wsa/x-tab-s204359"],
  ["Neil Young", "Hey Babe", "D# G# C# F# A# D#", "songsterr audit 2026-07-05 (14 views) https://www.songsterr.com/a/wsa/x-tab-s721321"],
  ["Elliott Smith", "no confidence man", "E A D G B E", "songsterr audit 2026-07-05 (13 views) https://www.songsterr.com/a/wsa/x-tab-s4229625"],
  ["Elliott Smith", "easy way out", "D# G# C# F# A# D#", "songsterr audit 2026-07-05 (10 views) https://www.songsterr.com/a/wsa/x-tab-s192186"],
  ["Sun Kil Moon", "Gentle Moon (Ver 2)", "E A D G B E", "songsterr audit 2026-07-05 (10 views) https://www.songsterr.com/a/wsa/x-tab-s251824"],
  ["Pavement", "No Life Singed Her", "C F A# D# G C", "songsterr audit 2026-07-05 (9 views) https://www.songsterr.com/a/wsa/x-tab-s4396513"],
  ["Red House Painters", "Smokey (Ver 1)", "E A D G B E", "songsterr audit 2026-07-05 (8 views) https://www.songsterr.com/a/wsa/x-tab-s5711940"],
  ["Red House Painters", "Smokey (Ver 2)", "E A D G B E", "songsterr audit 2026-07-05 (8 views) https://www.songsterr.com/a/wsa/x-tab-s5711940"],
  ["Paul McCartney", "For No One", "D G C F A D", "songsterr audit 2026-07-05 (7 views) https://www.songsterr.com/a/wsa/x-tab-s234363"],
  ["Neil Young", "Hippie Dream", "D A D G B E", "songsterr audit 2026-07-05 (6 views) https://www.songsterr.com/a/wsa/x-tab-s1743026"],
  ["Red House Painters", "Uncle Joe (Ver 2)", "D G C F A D", "songsterr audit 2026-07-05 (6 views) https://www.songsterr.com/a/wsa/x-tab-s3135908"],
  ["Bob Dylan", "Lay Down Your Weary Tune", "E A D G B E", "songsterr audit 2026-07-05 (5 views) https://www.songsterr.com/a/wsa/x-tab-s371231"],
  ["Karen Dalton", "Are You Leaving For The Country", "D A D F# A D", "songsterr audit 2026-07-05 (5 views) https://www.songsterr.com/a/wsa/x-tab-s207576"],
  ["Mark Kozelek", "Smokey (Acoustic)", "D# G# C# F# A# D#", "songsterr audit 2026-07-05 (5 views) https://www.songsterr.com/a/wsa/x-tab-s5208449"],
  ["Red House Painters", "Sundays and Holidays (Ver 2)", "D A D G A D", "songsterr audit 2026-07-05 (5 views) https://www.songsterr.com/a/wsa/x-tab-s5074488"],
  ["Elliott Smith", "dancing on the highway", "E A D G B E", "songsterr audit 2026-07-05 (4 views) https://www.songsterr.com/a/wsa/x-tab-s183324"],
  ["Sun Kil Moon", "Like The River", "C G C G C E", "songsterr audit 2026-07-05 (4 views) https://www.songsterr.com/a/wsa/x-tab-s3669406"],
  ["Sun Kil Moon", "Like The River", "C G C G C E", "songsterr audit 2026-07-05 (4 views) https://www.songsterr.com/a/wsa/x-tab-s3669406"],
  ["Elliott Smith", "our thing", "E A D G B E", "songsterr audit 2026-07-05 (3 views) https://www.songsterr.com/a/wsa/x-tab-s4724799"],
  ["Alex G", "Bad Man", "D A D G B E", "songsterr audit 2026-07-05 (2 views) https://www.songsterr.com/a/wsa/x-tab-s2779445"],
  ["Red House Painters", "Kavita (Ver 1)", "E A D G B E", "songsterr audit 2026-07-05 (2 views) https://www.songsterr.com/a/wsa/x-tab-s1824902"],
  ["Bill Callahan", "Lonely City", "D G C F A D", "songsterr audit 2026-07-05 (0 views) https://www.songsterr.com/a/wsa/x-tab-s5870589"],
  ["Bill Callahan", "Why Do Men Sing", "D G C F A D", "songsterr audit 2026-07-05 (0 views) https://www.songsterr.com/a/wsa/x-tab-s5869979"],
  ["Bob Dylan", "Dignity", "D# G# C# F# A# D#", "songsterr audit 2026-07-05 (0 views) https://www.songsterr.com/a/wsa/x-tab-s371399"],
  ["Father John Misty", "Mr Tillman", "E A D G B E", "songsterr audit 2026-07-05 (0 views) https://www.songsterr.com/a/wsa/x-tab-s3083928"],
  ["Father John Misty", "Only Son Of The Ladiesman", "E A D G B E", "songsterr audit 2026-07-05 (0 views) https://www.songsterr.com/a/wsa/x-tab-s185516"],
  ["Grizzly Bear", "A Simple Answer", "D# G# C# F# A# D#", "songsterr audit 2026-07-05 (0 views) https://www.songsterr.com/a/wsa/x-tab-s5856761"],
  ["Jason Molina", "Song Of The Road", "D# G# C# F# A# D#", "songsterr audit 2026-07-05 (0 views) https://www.songsterr.com/a/wsa/x-tab-s5894132"],
  ["Paul McCartney", "Souvenir", "D# G# C# F# A# D#", "songsterr audit 2026-07-05 (0 views) https://www.songsterr.com/a/wsa/x-tab-s234374"],
  ["Pavement", "Kentucky Cocktail", "D A D G B E", "songsterr audit 2026-07-05 (0 views) https://www.songsterr.com/a/wsa/x-tab-s1259262"],
  ["Smog", "Back In School", "C# F# B E G# C#", "songsterr audit 2026-07-05 (0 views) https://www.songsterr.com/a/wsa/x-tab-s5865930"],
  ["Songs: Ohia", "Back On Top", "C F A# D# G C", "songsterr audit 2026-07-05 (0 views) https://www.songsterr.com/a/wsa/x-tab-s5659893"],
  ["Sun Kil Moon", "Truck Driver", "A# F A# D# G C", "songsterr audit 2026-07-05 (0 views) https://www.songsterr.com/a/wsa/x-tab-s5020451"],
  ["Sun Kil Moon", "Truck Driver", "A# F A# D# G C", "songsterr audit 2026-07-05 (0 views) https://www.songsterr.com/a/wsa/x-tab-s5020451"],

  // --- Songsterr audit 2026-08-01 (machine-triaged): records whose
  // own tuning evidence was weak (meta/convention), single-version only,
  // Songsterr's absolute per-track tuning as the citation. ---
  ["Kurt Vile", "Wakin On A Pretty Day (ver 1)", "E A D G B E", "songsterr audit 2026-08-01 (2550 views) https://www.songsterr.com/a/wsa/x-tab-s1080863"],
  ["boygenius", "Satanist", "D A D G B E", "songsterr audit 2026-08-01 (1375 views) https://www.songsterr.com/a/wsa/x-tab-s708150"],
  ["Mac DeMarco", "Only You", "E A D G B E", "songsterr audit 2026-08-01 (287 views) https://www.songsterr.com/a/wsa/x-tab-s2311845"],
  ["The Everly Brothers", "Down In The Willow Garden", "D# G# C# F# A# D#", "songsterr audit 2026-08-01 (193 views) https://www.songsterr.com/a/wsa/x-tab-s192543"],
  ["Mac DeMarco", "Sweeter", "E A D G B E", "songsterr audit 2026-08-01 (133 views) https://www.songsterr.com/a/wsa/x-tab-s3068089"],
  ["Built to Spill", "Velvet Waltz", "D G C F A D", "songsterr audit 2026-08-01 (62 views) https://www.songsterr.com/a/wsa/x-tab-s2910522"],
  ["Mac DeMarco", "20200817 Proud True Toyota", "E A D G B E", "songsterr audit 2026-08-01 (9 views) https://www.songsterr.com/a/wsa/x-tab-s2713892"],
  ["Mac DeMarco", "Moving Like Mike", "D# G# C# F# A# D#", "songsterr audit 2026-08-01 (5 views) https://www.songsterr.com/a/wsa/x-tab-s3024110"],
  ["Mac DeMarco", "My Jean", "E A D G B E", "songsterr audit 2026-08-01 (2 views) https://www.songsterr.com/a/wsa/x-tab-s5673160"],
];
